
export const APP_INIT                = 'APP_INIT';
export const COGNITO_CONFIRM_REQUEST = 'COGNITO_CONFIRM_REQUEST';
export const COGNITO_CONFIRM_SUCCESS = 'COGNITO_CONFIRM_SUCCESS';
export const COGNITO_CONFIRM_FAIL    = 'COGNITO_CONFIRM_FAIL';
export const COGNITO_SIGNIN_REQUEST  = 'COGNITO_SIGNIN_REQUEST';
export const COGNITO_SIGNIN_SUCCESS  = 'COGNITO_SIGNIN_SUCCESS';
export const COGNITO_SIGNIN_FAIL     = 'COGNITO_SIGNIN_FAIL';
export const COGNITO_SIGNUP_REQUEST  = 'COGNITO_SIGNUP_REQUEST';
export const COGNITO_SIGNUP_SUCCESS  = 'COGNITO_SIGNUP_SUCCESS';
export const COGNITO_SIGNUP_FAIL     = 'COGNITO_SIGNUP_FAIL';
export const PERSIST_LOAD_SUCCESS    = 'PERSIST_LOAD_SUCCESS';
export const PERSIST_LOAD_FAIL       = 'PERSIST_LOAD_FAIL';
export const PERSIST_SAVE_REQUEST    = 'PERSIST_SAVE_REQUEST';
export const PERSIST_SAVE_SUCCESS    = 'PERSIST_SAVE_SUCCESS';
export const PERSIST_SAVE_FAIL       = 'PERSIST_SAVE_FAIL';
export const PERSIST_SAVE_SKIPPED    = 'PERSIST_SAVE_SKIPPED';

export const AWSUSERCONFIG_LOADED    = 'AWSUSERCONFIG_LOADED';
export const AWSUSERCONFIG_CHANGING  = 'AWSUSERCONFIG_CHANGING';



